import { Condition, Genders } from "../interfaces/Post";

export const genders = Object.values(Genders);
export const conditions = Object.values(Condition);
export const styles = [
  "Boho chic",
  "Clasic",
  "Casual",
  "Elegant",
  "Minimalist",
  "Office",
  "Romantic",
  "Sport",
  "Streetwear",
  "Altele",
];
export const brands = [
  "Nike",
  "Adidas",
  "Levi's",
  "Tommy Hilfiger",
  "Calvin Klein",
  "H&M",
  "Zara",
  "Gucci",
  "Prada",
  "Louis Vuitton",
  "Chanel",
  "Ralph Lauren",
  "Under Armour",
  "Puma",
  "Reebok",
  "The North Face",
  "Patagonia",
  "Columbia",
  "Timberland",
  "Pull&Bear",
  "Bershka",
  "Stradivarius",
  "Sinsay",
  "Reserved",
  "Gap",
  "Banana Republic",
  "Mango",
  "Diesel",
  "Superdry",
  "Guess",
  "Vans",
  "Converse",
  "Orsay",
  "Takko",
  "Terranova",
  "Oysho",
  "Cato",
  "Altele",
];

export const materials = [
  "Bumbac",
  "Cașmir",
  "Catifea",
  "Denim",
  "Elastan",
  "In",
  "Lână",
  "Mătase",
  "Nylon",
  "Piele",
  "Piele întoarsă",
  "Piele eco",
  "Polyester",
  "Poliamidă",
  "Vâscoză",
  "Altele",
];

export const categories = {
  category1: {
    îmbrăcăminte: {
      category2: [
        "topuri & bluze",
        "pantaloni",
        "fuste",
        "rochii",
        "geci",
        "salopete",
      ],
      category3: {
        "topuri & bluze": [
          "bluze",
          "bodies",
          "cămăși",
          "cardigane",
          "hanorace",
          "helănci",
          "maiouri",
          "pulovere",
          "topuri crop",
          "topuri & bluze",
          "tricouri",
        ],
        pantaloni: [
          "pantaloni scurți",
          "pantaloni de trening",
          "pantaloni cargo",
          "pantaloni de stofă",
          "jeans",
          "colanți",
          "pantaloni evazați",
          "pantaloni lungi",
          "pantaloni de piele",
        ],
        fuste: ["maxi", "mini", "midi", "fuste creion"],
        rochii: [
          "maxi",
          "mini",
          "midi",
          "rochii de vară",
          "rochii de seară",
          "rochii de cocktail",
          "rochii office",
          "rochii cămașă",
        ],
        geci: [
          "geci",
          "geci denim",
          "geci de piele",
          "geci de puf",
          "jachete subțiri",
          "sacouri",
          "veste",
          "paltoane",
          "paltoane de lână",
          "trenchuri",
          "pelerine de ploaie",
          "haine de blană",
        ],
        salopete: ["salopete lungi", "salopete scurte"],
      },
    },
    încălțăminte: {
      category2: ["pantofi sport", "cizme", "pantofi eleganți"],
      category3: {
        "pantofi sport": [
          "pantofi sport",
          "alergare",
          "fitness",
          "hiking",
          "yoga & pilates",
          "teniși & sneakers",
        ],
        cizme: [
          "ghete & bocanci",
          "cizme",
          "cizme cu toc",
          "cizme fără toc",
          "cizme peste genunchi",
        ],
        "pantofi eleganți": [
          "pantofi cu toc",
          "pantofi fără toc",
          "espadrile",
          "sandale cu toc",
          "sandale fără toc",
          "balerini",
        ],
      },
    },
  },
};

export const sizes = [
  "XXS",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
];

export const colors = [
  "alb",
  "bej",
  "galben",
  "galben-verzui",
  "grena",
  "mov",
  "lila",
  "portocaliu",
  "roșu",
  "roșu-deschis",
  "roșu-închis",
  "roz",
  "verde",
  "verde-deschis",
  "verde-inchis",
  "verde-oliva",
  "violet",
  "albastru",
  "albastru-deschis",
  "albastru-inchis",
  "ciano",
  "turcoaz",
  "visiniu",
  "maro",
  "roz-pal",
  "gri",
  "argintiu",
  "auriu",
  "negru",
];
